services:
  debian1:
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./ssh_keys:/root/.ssh
    healthcheck:
      test: ["CMD-SHELL", "sshd -T | grep 'sshd is running'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    dns: # In order to solve apt update cache error 
      - 8.8.8.8 #Google DNS
      - 8.8.4.4 #Google DNS
      - 1.1.1.1 #Cloudflare DNS
      - 1.1.4.4 #Cloudfare DNS


  debian2:
    build: .
    ports:
      - "2223:22"
    volumes:
      - ./ssh_keys:/root/.ssh
    healthcheck:
      test: ["CMD-SHELL", "sshd -T | grep 'sshd is running'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    dns: # In order to solve apt update cache error 
      - 8.8.8.8 #Google DNS
      - 8.8.4.4 #Google DNS
      - 1.1.1.1 #Cloudflare DNS
      - 1.1.4.4 #Cloudfare DNS
